### ISSUE TITLE
Unable to replicate results

### ISSUE THREAD

**Issue by b0xyfoXy** [zhuowei/CoreTrustDemo#1]
Thank you for putting this up! I tried to build and run the `spawn_root` binary with `bash` or `/bin/bash` as argument but I am getting the following:

```
failed to exec bash: No such file or directory
failed to exec /bin/bash: Undefined error: 0
```

I am on MacOS 11.5.3. Could you kindly provide some assistance?

**Comment by zhuowei** [comment]
Are you logged into the machine physically, not just over ssh? The `posix_spawnattr_set_persona_np` call only works if you're physically logged into the machine.

I've tested this on macOS 12.3.1 (Apple Silicon) and macOS 11.4b1 (20F5055c) (Intel) and it worked fine.

**Comment by b0xyfoXy** [comment]
I just figured out that might be the issue as well and tried doing it on the machine physically, it works. Thanks @zhuowei !

**Comment by zhuowei** [comment]
Good to hear. (You can run it over ssh - you just need to be physically logged in as well. I didn't put this in the README since I figured most people would test it from a local terminal anyways)
